name: Deploy

on:
  push:
    branches:
      - master
      - generate_with_actions
  pull_request:

jobs:
  Deploy:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync

      - name: Switch branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global push.autoSetupRemote true
          git switch -c gh-pages
          git merge master

      - name: Build
        run: uv run scripts/build.py

      - name: Deploy
        run: |
          git add docs/
          git commit -m "Build"
          git push -f
