name: Generate and Deploy RSS Feed

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate RSS feed
      uses: codesandtags/rss-generator-action@main
      with:
        FEED_TITLE: "静カニのブログ"
        FEED_DESCRIPTION: "静カニ(shizukani-cp)のブログです。雑多なことを投稿しています。"
        FEED_URL: "https://shizukani-cp.github.io/blog/rss.xml"
        FEED_PATH: "rss.xml"
        BASE_URL: "https://shizukani-cp.github.io/blog/"
        POSTS_DIR: "articles/"

    - name: Commit and push RSS feed
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add rss.xml
        git commit -m "Generate RSS feed"
        git push

    - name: Set up GitHub Pages
      uses: actions/configure-pages@v1

    - name: Upload artifact to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'rss.xml'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
